### ISSUE TITLE
No wrapping for long file names

### ISSUE THREAD

**Issue by tsjdev-apps** [ginomessmer/tmdm#8]
If I have long file names the file name is not wrapping. Please wrap the file name.

**Comment by rido-ramadan** [comment]
Example
![image](https://user-images.githubusercontent.com/3739579/86310791-0e7e1580-bc49-11ea-8d63-b523dcdf2493.png)

**Comment by ginomessmer** [comment]
Thanks for the heads-up @tsjdev-apps and @rido-ramadan. This should now be fixed in v2 #20. The update is live in the extensions store.
